import { SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ClerkHeader from "~/components/ClerkComponent";
import LoadingSpinner from "~/components/LoadingSpinner";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn, isLoaded } = useUser();

  if (!isLoaded) {
    return <LoadingSpinner />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkHeader />
    </>
  );
};

export default Home;
